version: '3'
services:
    api:
        restart: always
        container_name: api
        build:
            context: ../
            dockerfile: docker/Dockerfile.api
        expose:
            - "8000"
        ports: 
            - "8000:8000"
        command: bash -c "cd main && uvicorn API:app --reload --host 0.0.0.0 --port 8000"
    mlflow-server:
        restart: always
        container_name: mlflow-server
        build:
            context: ../
            dockerfile: docker/Dockerfile.mlflow
        expose:
            - "5000"
        ports:
            - "5000:5000"
        volumes:
            - "../tracking:/usr/src/app/tracking"
        command: mlflow server --backend-store-uri ./tracking --port 5000 --host 0.0.0.0
