version: '3'
services:
    api:
        restart: always
        container_name: api
        build:
            context: ../
            dockerfile: docker/Dockerfile-api
        expose:
            - "8000"
        ports: 
            - "8000:8000"
        command: uvicorn API:app --reload --host 0.0.0.0 --port 8000
