FROM python:3.8-buster


WORKDIR usr/src/app

# Copy and install dependencies
COPY ./src/requirements.txt .
RUN pip install -r requirements.txt

# Copy project files
COPY ./src/main/ .

# Copy docker entrypoints
COPY ./docker/entrypoints/docker-entrypoint-training.sh .
COPY ./docker/settings.sh .
