FROM python:3.7-buster

WORKDIR usr/src/app

RUN pip install -U pip

RUN pip install mlflow

EXPOSE 5000

# Add user "simple_user" with non-root privileges
RUN useradd -u 8877 simple_user

# Change to non-root privilege
USER simple_user
